apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dnsmasq.fullname" . }}
  labels:
    {{- include "dnsmasq.labels" . | nindent 4 }}
data:
{{- if .Values.upstreamDNS }}
  resolv.conf: |
  {{- range $server := .Values.upstreamDNS }}
    {{- print "nameserver " $server | nindent 4 }}
  {{- end }}
{{- end }}
  dnsmasq.conf: |
    interface={{ .Values.global.kubelan.vxlan.interface }}
    bind-interfaces
    port={{ .Values.service.port }}

  {{- if .Values.upstreamDNS }}
    resolv-file=/run/config/resolv.conf
  {{- end }}

  {{- with .Values.config }}
    {{- range $set := . }}
      {{- range $o, $v := $set }}
        {{- if eq (toString $v) "true" }}
          {{- $o | nindent 4 }}
        {{- else if ne (toString $v) "false" }}
          {{- print $o "=" $v | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
