image:
  repository: ghcr.io/devplayer0/dnsmasq
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

podAnnotations: {}

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
nodeSelector: {}
tolerations: []
affinity: {}

global:
  kubelan:
    image:
      repository: ghcr.io/devplayer0/kubelan
      pullPolicy: IfNotPresent
      tag: 0.2.1
    externalConfigMap:

    log_level: DEBUG
    extraServices: []
    vxlan:
      interface: kubelan
      vni: 7331
    hooks: {}

service:
  type: ClusterIP
  port: 53

debug: 'no'
upstreamDNS:
  - '1.1.1.1'
  - '8.8.8.8'
staticIP: '172.24.254.1/16'
routerNetwork: '172.24.0.0/16'
config:
  dns:
    domain: dnsmasq
  dhcp:
    dhcp-range: 172.24.1.1,172.24.253.254,2h
    dhcp-option: option:router,172.24.254.1
    dhcp-option: option:dns-server,172.24.254.1

persistence:
  enabled: false
  size: 64Mi
  storageClass: ''
